services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng

    ports:
      - '8080:8080'

    volumes:
      - ./searxng:/etc/searxng:rw

    env_file:
      - .env

    restart: unless-stopped

    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE

    logging:
      driver: json-file
      options:
        max-size: '1m'
        max-file: '1'
